services:
  smalland-dedicated:
    image: "ghcr.io/mrmightynighty/smalland-docker:latest"
    restart: unless-stopped
    volumes:
      - "./smalland:/home/steam/smalland-dedicated"
    environment:
      # Name of the server as it should appear on the server browser screen (for example "My Server")
      - SERVERNAME="Linux Docker Server"
      # World name which corresponds to the  save file name (for example "World")
      - WORLDNAME="World"
      # Password, leave it empty for open servers (for example "myPassword", can be empty "")
      - PASSWORD="CHANGEME"
      # Friendly fire between players, aka PVP (0 or 1)
      - FRIENDLYFIRE=0
      # Peaceful mode (0 or 1)
      - PEACEFULMODE=0
      # Keep inventory on death (0 or 1)
      - KEEPINVENTORY=0
      # Disable building wather deterioration (0 or 1)
      - NODETERIORATION=0
      # Private server is hidden on the server browser (0 or 1)
      - PRIVATE=0
      # Length of day in seconds (default is 1800 which is 30 minutess)
      - LENGTHOFDAYSECONDS=1800
      # Length of season in seconds (default is 10800 which is 3 hours)
      - LENGTHOFSEASONSECONDS=10800
      # Creature health modifier (20-300 default is 100)
      - CREATUREHEALTHMODIFIER=100
      # Creature damage modifier (20-300 default is 100)
      - CREATUREDAMAGEMODIFIER=100
      # Nourishment loss modifier (0-100 default is 100)
      - NOURISHMENTLOSSMODIFIER=100
      # Fall damage modifier (50-100 default is 100)
      - FALLDAMAGEMODIFIER=100
      # Additional configuration
      - PORT=7777
    ports:
      - "7777:7777/udp"
      - "7777:7777/tcp"
      - "7778:7778/udp"
      - "7778:7778/tcp"